### ISSUE TITLE
kube-system/configmaps: getting credentials: exec: exit status 254

### ISSUE THREAD

**Issue by daduskacpokus** [hashicorp/learn-terraform-provision-eks-cluster#8]
Faced this issue in terraform apply step with message

Error: Post "https://E8079842BCE9C149AFD5D78F04D17810.gr7.us-east-1.eks.amazonaws.com/api/v1/namespaces/kube-system/configmaps": getting credentials: exec: exit status 254

  on .terraform/modules/eks/terraform-aws-eks-12.0.0/aws_auth.tf line 62, in resource "kubernetes_config_map" "aws_auth":
  62: resource "kubernetes_config_map" "aws_auth" {

How can I solv it?

**Comment by CNoetzel** [comment]
I had the same problem. I've added the following provider to the eks-cluster.tf  as mentioned [here](https://github.com/hashicorp/learn-terraform-provision-eks-cluster/issues/2#issuecomment-618264288) and the apply step was successfully executed.

```
provider "kubernetes" {
  load_config_file       = "false"
  host                   = data.aws_eks_cluster.cluster.endpoint
  token                  = data.aws_eks_cluster_auth.cluster.token
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
}
```

**Comment by im2nguyen** [comment]
This has been addressed in #2  and a change has been merged into master, thanks for flagging this

**Comment by shadowrider-pl** [comment]
Bug still exists in 04/2021.
I had to add
`token                  = data.aws_eks_cluster_auth.cluster.token`
manually.

```
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = ">= 2.0.3"
    }
```

**Comment by im2nguyen** [comment]
@shadowrider-pl 

What do you mean? If you configured the AWI CLI correctly, the kubernetes.tf file should have the right config to authenticate to your EKS cluster.

```
provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  exec {
    api_version = "client.authentication.k8s.io/v1alpha1"
    command     = "aws"
    args = [
      "eks",
      "get-token",
      "--cluster-name",
      data.aws_eks_cluster.cluster.name
    ]
  }
}
```
